# This workflow is designed to be triggered externally (e.g., by a cron service).
# It runs a high-speed Playwright script that visits a URL and clicks coordinates.
name: High-Speed Clicker

# This trigger allows the workflow to be started on-demand via an API call.
on:
  workflow_dispatch:

jobs:
  run-clicker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Cache pip packages for faster subsequent runs
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Cache Playwright browsers to avoid re-downloading them every time
      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-chromium # Specific key for Chromium
          restore-keys: |
            ${{ runner.os }}-playwright-

      # Only install browsers if they are not found in the cache
      - name: Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: playwright install --with-deps chromium

      - name: Run the High-Speed Clicker script
        run: python fast_clicker.py